### ISSUE TITLE
HTTP sites will be marked as unsafe in July

### ISSUE THREAD

**Issue by obilodeau** [montrehack/montrehack.github.com#31]
We need to start thinking about what we will do since GitHub still doesn't allow us to use HTTPS with a custom domain.

Possible options:
* Cloudflare fronting with SSL (it's quite common apparently)
* [Netlify](https://www.netlify.com/github-pages-vs-netlify/) (asciidoctor guys are using it / looking at it)
* NorthSec's infrastructure
* Heroku
* Our own hosting

Ref: https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html

**Comment by Becojo** [comment]
Cloudflare ¯\_(ツ)_/¯

**Comment by obilodeau** [comment]
Fair point. The reason I haven't included it in the list is that some participants in the past mentioned their disgust of Cloudflare's practices regarding Tor and how it centralizes the Internet. These people were most vocal about NorthSec than MontréHack so I think I can add Cloudflare to the list.

**Comment by marc-etienne** [comment]
GitHub Pages now supports HTTPS with Let's Encrypt certs since May 1st. See: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

I've enabled HTTPS on montreahack.ca mid-May without issues. Closing.
