### ISSUE TITLE
Link preview cards

### ISSUE THREAD

**Issue by obilodeau** [montrehack/montrehack.github.com#66]
We should get link preview cards working.

NorthSec did it and they use jekyll I can see how it was accomplished there. It should also be relatively straightforward and document I think.

Anyone wants to give a hand and try? @alxbl, @h3xstream?

FLAG-b6eafa80ec5930884a4beb076a1c67bf

**Comment by alxbl** [comment]
This should be pretty easy with OpenGraph meta tags:

https://ogp.me/

More specifically:
> 
>    og:title - The title of your object as it should appear within the graph, e.g., "The Rock".
>    og:type - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.
>    og:image - An image URL which should represent your object within the graph.
>   og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "https://www.imdb.com/title/tt0117500/".
>
